name: Pre-Deployment Build Test

on:
  push:
    branches:
      - content
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner; adjust if using self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Ruby for GitHub-hosted runners
      - name: Setup Ruby
        if: runner.os == 'Linux' && runner.name != 'self-hosted'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      # Install Ruby manually for self-hosted runners
      - name: Install Ruby (Self-hosted only)
        if: runner.name == 'self-hosted'
        run: |
          curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-installer | bash
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"
          rbenv install 3.1.4
          rbenv global 3.1.4
          ruby -v

      # Build Jekyll site
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: development

      # Verify the build output
      - name: Verify Build Output
        run: |
          echo "Contents of the _site directory:"
          ls -l _site
