name: Pre-Deployment Build Test

on:
  push:
    branches:
      - content
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  # Change to self-hosted if required
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby (GitHub-hosted only)
        if: "!env.HOSTED_RUNNER"  # Environment variable set for self-hosted
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Install Ruby (Self-hosted only)
        if: "env.HOSTED_RUNNER"  # Self-hosted runner
        run: |
          curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-installer | bash
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"
          rbenv install 3.1.4
          rbenv global 3.1.4
          ruby -v

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: development

      - name: Verify Build Output
        run: |
          echo "Contents of the _site directory:"
          ls -l _site
